; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s9, Segoe UI
Gui Add, CheckBox, x16 y17 w100 h30, Run at Startup
Gui Add, CheckBox, x547 y424 w0 h0, CheckBox
Gui Add, Text, x112 y379 w40 h0, Keyboard Shortcut:
Gui Add, Text, x144 y367 w142 h30, Currently used database date:
Gui Add, Radio, x10 y359 w130 h30, Use internal database
Gui Add, Radio, x10 y389 w240 h30, Build database from 'INTEL Tool List' Excel file
Gui Add, CheckBox, x16 y81 w104 h23 +0xC00, Always on Top
Gui Add, Slider, x487 y54 w90 h20 Range0-100, 0
Gui Add, GroupBox, x8 y0 w297 h60, General Settings
Gui Add, GroupBox, x5 y148 w290 h180, Info Balloon
Gui Add, GroupBox, x8 y67 w300 h73, Main Program
Gui Add, Picture, x500 y20 w62 h26 0x6 +Border, TEL Logo.png
Gui Add, Text, x32 y102 w81 h23 +0x800, Transparency
Gui Add, Slider, x23 y125 w91 h23 Range0-100, 0
Gui Add, Text, x168 y161 w120 h23 +0x200, Activation method
Gui Add, Radio, x168 y184 w1603 h33, Quickly press CTRL twice
Gui Add, Text, x166 y81 w120 h23 +0x200, Activation method
Gui Add, Radio, x166 y103 w120 h36, Quickly press CTRL three times
Gui Add, Text, x13 y162 w137 h23 +0x200, Tool properties to display
Gui Add, CheckBox, x14 y195 w120 h23, Serial Number
Gui Add, CheckBox, x14 y219 w120 h23, Warranty End
Gui Add, CheckBox, x13 y267 w120 h23, Serial Number
Gui Add, CheckBox, x14 y243 w120 h23, Process
Gui Add, Button, x18 y430 w93 h23, $Browse for file
Gui Add, GroupBox, x7 y337 w1698 h716, GroupBox

Gui Show, w313 h500, Settings Menu.ahk (Clone)
Return

GuiEscape:
GuiClose:
    ExitApp
